export App from 'containers/App'
export Dashboard from 'containers/Dashboard'
export Behavior from 'containers/Behavior'
export LoginOrRegister from 'containers/LoginOrRegister'
export NotFound from 'containers/NotFound'